### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by mmsesay** [mmsesay/catalog-of-my-things#33]
In the Issue, we set up our project's [kanban board](https://github.com/mmsesay/catalog-of-my-things/projects/1) and shared the tasks.
We are a 3 member team and the tasks are shared as follows:

- @mmsesay as Team Member 1
- @see-why as Team Member 2
- @HENRYKC24 as Team Member 3

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
